export const stations = [
  {
    FID: "1",
    id: "501",
    nimi: "Hanasaari",
    namn: "Hanaholmen",
    name: "Hanasaari",
    osoite: "Hanasaarenranta 1",
    adress: "Hanaholmsstranden 1",
    kaupunki: "Espoo",
    stad: "Esbo",
    operaattor: "CityBike Finland",
    kapasiteet: "10",
    x: "24.840319",
    y: "60.16582",
  },
  {
    FID: "329",
    id: "267",
    nimi: "Roihupelto",
    namn: "Kasåkern",
    name: "Roihupelto",
    osoite: "Viilarintie 6",
    adress: "Filarvägen 6",
    kaupunki: "",
    stad: "",
    operaattor: "",
    kapasiteet: "16",
    x: "25.0550878014734",
    y: "60.2093671231044",
  },
];

export const trips = [
  {
    departureTime: "NL/AB",
    returnTime: "123",
    departureStationId: "normal",
    departureStationName: "asd",
    returnStationId: "asd",
    returnStationName: "asd",
    distanceInMeters: "asd",
    durationInSeconds: "asd",
  },
  {
    departureTime: "NL/AB",
    returnTime: "123",
    departureStationId: "normal",
    departureStationName: "asd",
    returnStationId: "asd",
    returnStationName: "asd",
    distanceInMeters: "asd",
    durationInSeconds: "asd",
  },
];
